"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.LocationPreferenceErrorCodes = exports.SettingsErrorCodes = exports.CompanyErrorCodes = exports.PublicProfileErrorCodes = exports.SavedJobErrorCodes = exports.PaymentErrorCodes = exports.AIErrorCodes = exports.MessageErrorCodes = exports.NotificationErrorCodes = exports.LocationErrorCodes = exports.VerificationErrorCodes = exports.ApplicationErrorCodes = exports.JobErrorCodes = exports.UploadErrorCodes = exports.UserErrorCodes = void 0;
// libs/common/enums/error-codes.domain.ts
var UserErrorCodes;
(function (UserErrorCodes) {
    UserErrorCodes["USER_NOT_FOUND"] = "USER_NOT_FOUND";
    UserErrorCodes["PROFILE_NOT_FOUND"] = "PROFILE_NOT_FOUND";
    UserErrorCodes["PROFILE_INCOMPLETE"] = "PROFILE_INCOMPLETE";
    UserErrorCodes["PROFILE_NOT_CREATED"] = "PROFILE_NOT_CREATED";
    UserErrorCodes["PROFILE_ALREADY_EXISTS"] = "PROFILE_ALREADY_EXISTS";
    UserErrorCodes["INVALID_PROFILE_DATA"] = "INVALID_PROFILE_DATA";
    UserErrorCodes["PROFILE_UPDATE_FAILED"] = "PROFILE_UPDATE_FAILED";
})(UserErrorCodes || (exports.UserErrorCodes = UserErrorCodes = {}));
var UploadErrorCodes;
(function (UploadErrorCodes) {
    UploadErrorCodes["FILE_TOO_LARGE"] = "FILE_TOO_LARGE";
    UploadErrorCodes["INVALID_FILE_TYPE"] = "INVALID_FILE_TYPE";
    UploadErrorCodes["FILE_UPLOAD_FAILED"] = "FILE_UPLOAD_FAILED";
    UploadErrorCodes["FILE_NOT_FOUND"] = "FILE_NOT_FOUND";
    UploadErrorCodes["FILE_DELETE_FAILED"] = "FILE_DELETE_FAILED";
    UploadErrorCodes["INVALID_FILE_FORMAT"] = "INVALID_FILE_FORMAT";
    UploadErrorCodes["FILE_CORRUPTED"] = "FILE_CORRUPTED";
    UploadErrorCodes["STORAGE_QUOTA_EXCEEDED"] = "STORAGE_QUOTA_EXCEEDED";
})(UploadErrorCodes || (exports.UploadErrorCodes = UploadErrorCodes = {}));
var JobErrorCodes;
(function (JobErrorCodes) {
    JobErrorCodes["JOB_NOT_FOUND"] = "JOB_NOT_FOUND";
    JobErrorCodes["JOB_ALREADY_CLOSED"] = "JOB_ALREADY_CLOSED";
    JobErrorCodes["JOB_ALREADY_EXPIRED"] = "JOB_ALREADY_EXPIRED";
    JobErrorCodes["JOB_NOT_EDITABLE"] = "JOB_NOT_EDITABLE";
    JobErrorCodes["JOB_NOT_DELETABLE"] = "JOB_NOT_DELETABLE";
    JobErrorCodes["JOB_CREATION_FAILED"] = "JOB_CREATION_FAILED";
    JobErrorCodes["INVALID_JOB_STATUS"] = "INVALID_JOB_STATUS";
    JobErrorCodes["JOB_LIMIT_REACHED"] = "JOB_LIMIT_REACHED";
    JobErrorCodes["DRAFT_SAVE_FAILED"] = "DRAFT_SAVE_FAILED";
    JobErrorCodes["PROFILE_COMPLETION_REQUIRED"] = "PROFILE_COMPLETION_REQUIRED";
    JobErrorCodes["COMPANY_NOT_VERIFIED"] = "COMPANY_NOT_VERIFIED";
    JobErrorCodes["VERIFICATION_PENDING"] = "VERIFICATION_PENDING";
})(JobErrorCodes || (exports.JobErrorCodes = JobErrorCodes = {}));
var ApplicationErrorCodes;
(function (ApplicationErrorCodes) {
    ApplicationErrorCodes["APPLICATION_NOT_FOUND"] = "APPLICATION_NOT_FOUND";
    ApplicationErrorCodes["APPLICATION_SUBMISSION_FAILED"] = "APPLICATION_SUBMISSION_FAILED";
    ApplicationErrorCodes["NO_APPLICATIONS_FOUND"] = "NO_APPLICATIONS_FOUND";
    ApplicationErrorCodes["ALREADY_APPLIED"] = "ALREADY_APPLIED";
    ApplicationErrorCodes["JOB_NOT_ACCEPTING_APPLICATIONS"] = "JOB_NOT_ACCEPTING_APPLICATIONS";
    ApplicationErrorCodes["JOB_EXPIRED"] = "JOB_EXPIRED";
    ApplicationErrorCodes["JOB_CLOSED"] = "JOB_CLOSED";
    ApplicationErrorCodes["CANNOT_APPLY_OWN_JOB"] = "CANNOT_APPLY_OWN_JOB";
    ApplicationErrorCodes["RESUME_REQUIRED"] = "RESUME_REQUIRED";
    ApplicationErrorCodes["INVALID_RESUME"] = "INVALID_RESUME";
    ApplicationErrorCodes["RESUME_NOT_FOUND"] = "RESUME_NOT_FOUND";
    ApplicationErrorCodes["SCREENING_ANSWERS_REQUIRED"] = "SCREENING_ANSWERS_REQUIRED";
    ApplicationErrorCodes["SCREENING_ANSWERS_INVALID"] = "SCREENING_ANSWERS_INVALID";
    ApplicationErrorCodes["SCREENING_ANSWER_TOO_SHORT"] = "SCREENING_ANSWER_TOO_SHORT";
    ApplicationErrorCodes["REQUIRED_QUESTION_MISSING"] = "REQUIRED_QUESTION_MISSING";
    ApplicationErrorCodes["INVALID_QUESTION_ID"] = "INVALID_QUESTION_ID";
    ApplicationErrorCodes["PROFILE_COMPLETION_TOO_LOW"] = "PROFILE_COMPLETION_TOO_LOW";
    ApplicationErrorCodes["CANNOT_WITHDRAW"] = "CANNOT_WITHDRAW";
    ApplicationErrorCodes["ALREADY_WITHDRAWN"] = "ALREADY_WITHDRAWN";
    ApplicationErrorCodes["CANNOT_WITHDRAW_REJECTED"] = "CANNOT_WITHDRAW_REJECTED";
    ApplicationErrorCodes["INVALID_STATUS_TRANSITION"] = "INVALID_STATUS_TRANSITION";
    ApplicationErrorCodes["WITHDRAWN_APPLICATION_LOCKED"] = "WITHDRAWN_APPLICATION_LOCKED";
    ApplicationErrorCodes["REJECTED_APPLICATION_LOCKED"] = "REJECTED_APPLICATION_LOCKED";
    ApplicationErrorCodes["STATUS_UPDATE_FAILED"] = "STATUS_UPDATE_FAILED";
    ApplicationErrorCodes["NOT_YOUR_APPLICATION"] = "NOT_YOUR_APPLICATION";
    ApplicationErrorCodes["NOT_YOUR_JOB"] = "NOT_YOUR_JOB";
    ApplicationErrorCodes["EMPLOYER_PROFILE_REQUIRED"] = "EMPLOYER_PROFILE_REQUIRED";
    ApplicationErrorCodes["AI_SCORE_CALCULATION_FAILED"] = "AI_SCORE_CALCULATION_FAILED";
    ApplicationErrorCodes["AI_SCORE_NOT_AVAILABLE"] = "AI_SCORE_NOT_AVAILABLE";
    ApplicationErrorCodes["PROFILE_INCOMPLETE_FOR_SCORING"] = "PROFILE_INCOMPLETE_FOR_SCORING";
    ApplicationErrorCodes["AI_SCORE_TIMEOUT"] = "AI_SCORE_TIMEOUT";
    ApplicationErrorCodes["APPLICATION_CLOSED"] = "APPLICATION_CLOSED";
    ApplicationErrorCodes["APPLICATION_EXPIRED"] = "APPLICATION_EXPIRED";
    ApplicationErrorCodes["INVALID_APPLICATION_STATUS"] = "INVALID_APPLICATION_STATUS";
    ApplicationErrorCodes["COVER_LETTER_REQUIRED"] = "COVER_LETTER_REQUIRED";
    ApplicationErrorCodes["APPLICATION_LIMIT_REACHED"] = "APPLICATION_LIMIT_REACHED";
})(ApplicationErrorCodes || (exports.ApplicationErrorCodes = ApplicationErrorCodes = {}));
var VerificationErrorCodes;
(function (VerificationErrorCodes) {
    VerificationErrorCodes["VERIFICATION_NOT_FOUND"] = "VERIFICATION_NOT_FOUND";
    VerificationErrorCodes["EMPLOYER_PROFILE_NOT_FOUND"] = "EMPLOYER_PROFILE_NOT_FOUND";
    VerificationErrorCodes["ALREADY_VERIFIED"] = "ALREADY_VERIFIED";
    VerificationErrorCodes["VERIFICATION_PENDING"] = "VERIFICATION_PENDING";
    VerificationErrorCodes["VERIFICATION_UNDER_REVIEW"] = "VERIFICATION_UNDER_REVIEW";
    VerificationErrorCodes["VERIFICATION_REJECTED"] = "VERIFICATION_REJECTED";
    VerificationErrorCodes["INVALID_VERIFICATION_DOCUMENT"] = "INVALID_VERIFICATION_DOCUMENT";
    VerificationErrorCodes["DOCUMENT_UPLOAD_FAILED"] = "DOCUMENT_UPLOAD_FAILED";
    VerificationErrorCodes["DOCUMENT_EXPIRED"] = "DOCUMENT_EXPIRED";
    VerificationErrorCodes["DOCUMENT_TOO_LARGE"] = "DOCUMENT_TOO_LARGE";
    VerificationErrorCodes["UNSUPPORTED_DOCUMENT_TYPE"] = "UNSUPPORTED_DOCUMENT_TYPE";
    VerificationErrorCodes["VERIFICATION_REQUIRED"] = "VERIFICATION_REQUIRED";
    VerificationErrorCodes["PROFILE_INCOMPLETE_FOR_VERIFICATION"] = "PROFILE_INCOMPLETE_FOR_VERIFICATION";
    VerificationErrorCodes["RESUBMISSION_LIMIT_REACHED"] = "RESUBMISSION_LIMIT_REACHED";
    VerificationErrorCodes["CANNOT_RESUBMIT_YET"] = "CANNOT_RESUBMIT_YET";
    VerificationErrorCodes["VERIFICATION_SUBMISSION_FAILED"] = "VERIFICATION_SUBMISSION_FAILED";
    VerificationErrorCodes["VERIFICATION_UPDATE_FAILED"] = "VERIFICATION_UPDATE_FAILED";
})(VerificationErrorCodes || (exports.VerificationErrorCodes = VerificationErrorCodes = {}));
var LocationErrorCodes;
(function (LocationErrorCodes) {
    LocationErrorCodes["LOCATION_NOT_FOUND"] = "LOCATION_NOT_FOUND";
    LocationErrorCodes["INVALID_LOCATION_DATA"] = "INVALID_LOCATION_DATA";
    LocationErrorCodes["LOCATION_SERVICE_UNAVAILABLE"] = "LOCATION_SERVICE_UNAVAILABLE";
    LocationErrorCodes["LOCATION_SERVICE_ERROR"] = "LOCATION_SERVICE_ERROR";
    LocationErrorCodes["LOCATION_API_UNAVAILABLE"] = "LOCATION_API_UNAVAILABLE";
    LocationErrorCodes["GEOCODING_FAILED"] = "GEOCODING_FAILED";
})(LocationErrorCodes || (exports.LocationErrorCodes = LocationErrorCodes = {}));
var NotificationErrorCodes;
(function (NotificationErrorCodes) {
    NotificationErrorCodes["NOTIFICATION_NOT_FOUND"] = "NOTIFICATION_NOT_FOUND";
    NotificationErrorCodes["NOTIFICATION_SEND_FAILED"] = "NOTIFICATION_SEND_FAILED";
    NotificationErrorCodes["NOTIFICATION_FAILED"] = "NOTIFICATION_FAILED";
    NotificationErrorCodes["INVALID_NOTIFICATION_CHANNEL"] = "INVALID_NOTIFICATION_CHANNEL";
    NotificationErrorCodes["NOTIFICATION_PREFERENCES_NOT_FOUND"] = "NOTIFICATION_PREFERENCES_NOT_FOUND";
})(NotificationErrorCodes || (exports.NotificationErrorCodes = NotificationErrorCodes = {}));
var MessageErrorCodes;
(function (MessageErrorCodes) {
    MessageErrorCodes["MESSAGE_NOT_FOUND"] = "MESSAGE_NOT_FOUND";
    MessageErrorCodes["CONVERSATION_NOT_FOUND"] = "CONVERSATION_NOT_FOUND";
    MessageErrorCodes["CANNOT_MESSAGE_SELF"] = "CANNOT_MESSAGE_SELF";
    MessageErrorCodes["MESSAGE_SEND_FAILED"] = "MESSAGE_SEND_FAILED";
    MessageErrorCodes["BLOCKED_USER"] = "BLOCKED_USER";
    MessageErrorCodes["CONVERSATION_CLOSED"] = "CONVERSATION_CLOSED";
    MessageErrorCodes["INVALID_MESSAGE_TYPE"] = "INVALID_MESSAGE_TYPE";
    MessageErrorCodes["MESSAGE_TOO_LONG"] = "MESSAGE_TOO_LONG";
    MessageErrorCodes["ENCRYPTION_FAILED"] = "ENCRYPTION_FAILED";
    MessageErrorCodes["DECRYPTION_FAILED"] = "DECRYPTION_FAILED";
    MessageErrorCodes["CONVERSATION_ACCESS_DENIED"] = "CONVERSATION_ACCESS_DENIED";
    MessageErrorCodes["ROLE_MISMATCH"] = "ROLE_MISMATCH";
})(MessageErrorCodes || (exports.MessageErrorCodes = MessageErrorCodes = {}));
var AIErrorCodes;
(function (AIErrorCodes) {
    AIErrorCodes["AI_SERVICE_UNAVAILABLE"] = "AI_SERVICE_UNAVAILABLE";
    AIErrorCodes["AI_GENERATION_FAILED"] = "AI_GENERATION_FAILED";
    AIErrorCodes["AI_QUOTA_EXCEEDED"] = "AI_QUOTA_EXCEEDED";
    AIErrorCodes["INVALID_AI_PROMPT"] = "INVALID_AI_PROMPT";
    AIErrorCodes["AI_TIMEOUT"] = "AI_TIMEOUT";
})(AIErrorCodes || (exports.AIErrorCodes = AIErrorCodes = {}));
var PaymentErrorCodes;
(function (PaymentErrorCodes) {
    PaymentErrorCodes["PAYMENT_FAILED"] = "PAYMENT_FAILED";
    PaymentErrorCodes["INVALID_PAYMENT_METHOD"] = "INVALID_PAYMENT_METHOD";
    PaymentErrorCodes["PAYMENT_REQUIRED"] = "PAYMENT_REQUIRED";
    PaymentErrorCodes["SUBSCRIPTION_EXPIRED"] = "SUBSCRIPTION_EXPIRED";
    PaymentErrorCodes["INSUFFICIENT_CREDITS"] = "INSUFFICIENT_CREDITS";
})(PaymentErrorCodes || (exports.PaymentErrorCodes = PaymentErrorCodes = {}));
var SavedJobErrorCodes;
(function (SavedJobErrorCodes) {
    SavedJobErrorCodes["SAVED_JOB_NOT_FOUND"] = "SAVED_JOB_NOT_FOUND";
    SavedJobErrorCodes["JOB_ALREADY_SAVED"] = "JOB_ALREADY_SAVED";
    SavedJobErrorCodes["CANNOT_SAVE_OWN_JOB"] = "CANNOT_SAVE_OWN_JOB";
    SavedJobErrorCodes["SAVED_JOBS_LIMIT_REACHED"] = "SAVED_JOBS_LIMIT_REACHED";
})(SavedJobErrorCodes || (exports.SavedJobErrorCodes = SavedJobErrorCodes = {}));
var PublicProfileErrorCodes;
(function (PublicProfileErrorCodes) {
    PublicProfileErrorCodes["SEEKER_PROFILE_NOT_PUBLIC"] = "SEEKER_PROFILE_NOT_PUBLIC";
    PublicProfileErrorCodes["COMPANY_PROFILE_NOT_PUBLIC"] = "COMPANY_PROFILE_NOT_PUBLIC";
})(PublicProfileErrorCodes || (exports.PublicProfileErrorCodes = PublicProfileErrorCodes = {}));
var CompanyErrorCodes;
(function (CompanyErrorCodes) {
    CompanyErrorCodes["COMPANY_NOT_FOUND"] = "COMPANY_NOT_FOUND";
    CompanyErrorCodes["COMPANY_SLUG_TAKEN"] = "COMPANY_SLUG_TAKEN";
    CompanyErrorCodes["INVALID_COMPANY_DATA"] = "INVALID_COMPANY_DATA";
})(CompanyErrorCodes || (exports.CompanyErrorCodes = CompanyErrorCodes = {}));
var SettingsErrorCodes;
(function (SettingsErrorCodes) {
    SettingsErrorCodes["SETTINGS_NOT_FOUND"] = "SETTINGS_NOT_FOUND";
    SettingsErrorCodes["EMAIL_UNCHANGED"] = "EMAIL_UNCHANGED";
    SettingsErrorCodes["PASSWORD_UNCHANGED"] = "PASSWORD_UNCHANGED";
    SettingsErrorCodes["INVALID_PASSWORD"] = "INVALID_PASSWORD";
})(SettingsErrorCodes || (exports.SettingsErrorCodes = SettingsErrorCodes = {}));
var LocationPreferenceErrorCodes;
(function (LocationPreferenceErrorCodes) {
    LocationPreferenceErrorCodes["MAX_LOCATIONS_REACHED"] = "MAX_LOCATIONS_REACHED";
    LocationPreferenceErrorCodes["LOCATION_ALREADY_ADDED"] = "LOCATION_ALREADY_ADDED";
    LocationPreferenceErrorCodes["LOCATION_PREFERENCE_NOT_FOUND"] = "LOCATION_PREFERENCE_NOT_FOUND";
})(LocationPreferenceErrorCodes || (exports.LocationPreferenceErrorCodes = LocationPreferenceErrorCodes = {}));
