export declare enum AuditAction {
  LOGIN_SUCCESS = "LOGIN_SUCCESS",
  LOGIN_FAILURE = "LOGIN_FAILURE",
  LOGIN_LOCKED = "LOGIN_LOCKED",
  LOGOUT = "LOGOUT",
  LOGOUT_ALL = "LOGOUT_ALL",
  REGISTER = "REGISTER",
  EMAIL_VERIFIED = "EMAIL_VERIFIED",
  EMAIL_VERIFICATION_RESENT = "EMAIL_VERIFICATION_RESENT",
  PASSWORD_CHANGED = "PASSWORD_CHANGED",
  PASSWORD_RESET_REQUESTED = "PASSWORD_RESET_REQUESTED",
  PASSWORD_RESET_COMPLETED = "PASSWORD_RESET_COMPLETED",
  SESSION_REVOKED = "SESSION_REVOKED",
  SESSION_REVOKED_ALL = "SESSION_REVOKED_ALL",
  SESSION_ROTATED = "SESSION_ROTATED",
  SESSION_EXPIRED = "SESSION_EXPIRED",
  OAUTH_LOGIN = "OAUTH_LOGIN",
  OAUTH_ACCOUNT_LINKED = "OAUTH_ACCOUNT_LINKED",
  ACCOUNT_DELETED = "ACCOUNT_DELETED",
  ACCOUNT_DEACTIVATED = "ACCOUNT_DEACTIVATED", // ✅ NEW
  ACCOUNT_DELETION_CANCELLED = "ACCOUNT_DELETION_CANCELLED", // ✅ NEW
  MOBILE_LOGIN = "MOBILE_LOGIN",
  MOBILE_TOKEN_REFRESHED = "MOBILE_TOKEN_REFRESHED",
  MOBILE_LOGOUT = "MOBILE_LOGOUT",
}
export type AuditStatus = "SUCCESS" | "FAILURE";
export interface AuditRequestContext {
  ip?: string;
  userAgent?: string;
  sessionId?: string;
}
export interface AuditLogEntry {
  action: AuditAction;
  status: AuditStatus;
  userId?: string;
  req?: AuditRequestContext;
  metadata?: Record<string, any>;
}
