-- AlterEnum
ALTER TYPE "ApplicationStatus" ADD VALUE IF NOT EXISTS 'INTERVIEW';
ALTER TYPE "ApplicationStatus" ADD VALUE IF NOT EXISTS 'OFFERED';
ALTER TYPE "ApplicationStatus" ADD VALUE IF NOT EXISTS 'HIRED';
